### ISSUE TITLE
When used in conjunction with supertab, literal tabs can no longer be inserted using <tab> key

### ISSUE THREAD

**Issue by karlmoritz** [drmingdrmer/xptemplate#29]
When using the setup as described in the FAQ to integrate xptemplate with supertab, vim no longer inserts a literal tab character (or spaces) when <tab> is pressed on a newline or after a space etc.

I'm not entirely sure if this problem is due to xptemplate / the way that xptemplate interfaces with supertab, but suspect it might be, as supertab and xptemplate individually do not have this problem (i.e. when no completion is possible, a tab is inserted).

Any hints on how to resolve this would be greatly appreciated.

**Comment by drmingdrmer** [comment]
It seems the latest supertab had changed something that this solution does not work any more.

Here is the solution for newest supertab( since  ervandew/supertab@b0ca47f4570385043f270f9278ba6d50d1d2fa00 ).
Put following lines into `~/.vimrc`:

```vim
" Prevent supertab from mapping <tab> to anything.
let g:SuperTabMappingForward = '<Plug>xpt_void'

" Tell XPTemplate what to fall back to, if nothing matches.
" Original SuperTab() yields nothing if g:SuperTabMappingForward was set to
" something it does not know.
let g:xptemplate_fallback = '<C-r>=XPTwrapSuperTab("n")<CR>'

fun! XPTwrapSuperTab(command) "{{{
    let v = SuperTab(a:command)
    if v == ''
        " Change \<Tab> to whatever you want, when neither XPTemplate or
        " supertab needs to do anything.
        return "\<Tab>"
    else
        return v
    end
endfunction "}}}
```

With former version of supertab, it is safe to redefine `g:SuperTabMappingForward` to any keystrokes. But the latest supertab does not yield literal `<tab>` if `g:SuperTabMappingForward` was set to something supertab does not know.

**Comment by talek** [comment]
Yes, it's working for me! Many thanks.
