### ISSUE TITLE
Conflict with CtrlP

### ISSUE THREAD

**Issue by blub123muh** [drmingdrmer/xptemplate#79]
Dear drmingdrmer,

Im experiencing a major conflict with [CtrlP](https://github.com/kien/ctrlp.vim).
Basically: I hit Ctrl-P and get an error on every single key I press.

- Error detected while processing function <SNR>73_XPTupdateTyping[1]..<SNR>73_XPTupdate:
- line    1:
- E121: Undefined variable: b:xptemplateData

Please let me know whether this problem is only caused in my setup.

Best regards,
lpag

**Comment by drmingdrmer** [comment]
I see that this problem is caused by some incorrect order of VIM event triggering.

Normally `CursorMove` event will only triggered after `BufEnter`. XPT does initialize in event `BufEnter`. But it seems ctrl-p causes it trigger `CursorMove` event before `BufEnter` when opening ctrl-p window.

I am going to add some test and fix it soon.

And a lot thanks for reporting this issue 👍 👍

**Comment by drmingdrmer** [comment]
ctrlp turns off autocommand before opening file list window, that causes XPTemplate fails to init buffer data.

This issue was fixed in latest master: XPTempalte always tries to initialize buffer data when updating tracking marks
