### ISSUE TITLE
cannot go back when select the last ^arg`

### ISSUE THREAD

**Issue by huaihuaiVV** [drmingdrmer/xptemplate#82]
![parallels picture](https://cloud.githubusercontent.com/assets/5601971/20821827/db8851ba-b880-11e6-8fa0-515ea18b206c.png)

setting:

let g:xptemplate_nav_next = "<C-j>"
let g:xptemplate_nav_prev = "<C-k>"
" let g:xptemplate_nav_cancel = "<C-c>"
let g:xptemplate_fallback = ""
let g:xptemplate_goback = "<C-b>"

when i select the last argument,
then i use <C-k> to go back,
i can not go back,

**Comment by huaihuaiVV** [comment]
let g:xptemplate_nav_next = "\<C-j\>"
let g:xptemplate_nav_prev = "\<C-k\>"
" let g:xptemplate_nav_cancel = "\<C-c\>"
let g:xptemplate_fallback = ""
let g:xptemplate_goback = "\<C-b\>"



when i select the last argument,
then i use C-K go back,
i can not go back,

**Comment by drmingdrmer** [comment]
When cursor focuses on the last placeholder, snippet rendering is over.
Because a user does not need `<c-j>` and `<c-k>` anymore to go to another placeholder.

Intuitively, after typing some text on the last placeholder, a user might believe snippet rendering is over.
He would expect `<c-j>` or `<c-k>` to be reset to his own key mapping, but not XPT's mapping.

On the last placeholder, if `<c-j>` and `<c-k>` is still working, a user then need another keystroke to turn off snippet rendering.
I most cases it is not very convenient. 

If you really need to go to the previous placeholder from that last, you can add another empty placeholder to your snippet:
```
XPT fun
int foo(`a^, `b^`^);
```

Then you can edit `b` and go back to `a`.

But personally I prefer not to add ";" in a function snippet and use an empty placeholder at line end:

```
XPT fun
int foo(`a^, `b^)`^
```
